sudo: required
language: node_js
node_js:
    - "10"

notifications:
    disabled: true

services:
    - docker

before_install:
    # install heroku CLI
    - wget -qO- https://toolbelt.heroku.com/install.sh | sh
    # login to docker registries (dockerhub + heroku)
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - echo "$HEROKU_PASSWORD" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com

install:
    # install deps
    - yarn install

script:
    - echo "npm test temporarily disabled"
    - yarn build
    - docker build -t joseaay/qa-cyborg .
    - docker tag joseaay/qa-cyborg registry.heroku.com/$HEROKU_APP_NAME/web

deploy:
    provider: script
    script:
        # push to dockerhub
        docker push joseaay/qa-cyborg;
        docker push registry.heroku.com/$HEROKU_APP_NAME/web;
        heroku container:release web --app $HEROKU_APP_NAME
    on:
        branch: master
